const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("pos", {
  setupStatus: () => ipcRenderer.invoke("auth:setup-status"),
  setupAdmin: (details) => ipcRenderer.invoke("auth:setup-admin", details),
  login: (credentials) => ipcRenderer.invoke("auth:login", credentials),
  logout: () => ipcRenderer.invoke("auth:logout"),
  currentUser: () => ipcRenderer.invoke("auth:current-user"),
  listProducts: () => ipcRenderer.invoke("products:list"),
  listCategories: () => ipcRenderer.invoke("categories:list"),
  saveCategory: (category) => ipcRenderer.invoke("categories:save", category),
  deleteCategory: (id) => ipcRenderer.invoke("categories:delete", id),
  saveProduct: (product) => ipcRenderer.invoke("products:save", product),
  importProductsExcel: () => ipcRenderer.invoke("products:import-excel"),
  deleteProduct: (id) => ipcRenderer.invoke("products:delete", id),
  createSale: (sale) => ipcRenderer.invoke("sales:create", sale),
  listSales: (filters) => ipcRenderer.invoke("sales:list", filters),
  getReport: (filters) => ipcRenderer.invoke("reports:get", filters),
  listUsers: () => ipcRenderer.invoke("users:list"),
  saveUser: (user) => ipcRenderer.invoke("users:save", user),
  deleteUser: (id) => ipcRenderer.invoke("users:delete", id),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  saveSettings: (settings) => ipcRenderer.invoke("settings:save", settings),
  exportCsv: (filters) => ipcRenderer.invoke("export:csv", filters),
  exportBackup: () => ipcRenderer.invoke("backup:export"),
  restoreBackup: () => ipcRenderer.invoke("backup:restore"),
  listPrinters: () => ipcRenderer.invoke("printers:list"),
  printReceipt: (receipt) => ipcRenderer.invoke("receipt:print", receipt),
});
